<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
                      "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head><title>Page Not Found</title></head>
<style type="text/css">
body { background: #171717; }
h1.error { color: #D5C0B3; font-size: 48px; font-weight: normal; line-height: 52px; padding-top: 200px; padding-bottom: 20px; text-align: center; }
p.error {color: #82807E; font-size: 24px; text-align: center; padding-bottom: 200px;}
</style>
<body>
<h1 class="error">The page you were looking for doesn't exist.</h1>
<p class="error">You may have mistyped the address or the page may have moved</p>
</body>
</html>
